/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as IndexImport } from './routes/index';
import { Route as DodoIndexImport } from './routes/dodo/index';

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const DodoIndexRoute = DodoIndexImport.update({
  path: '/dodo/',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/dodo/': {
      id: '/dodo/';
      path: '/dodo';
      fullPath: '/dodo';
      preLoaderRoute: typeof DodoIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/dodo': typeof DodoIndexRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/dodo': typeof DodoIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/dodo/': typeof DodoIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/dodo';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/dodo';
  id: '__root__' | '/' | '/dodo/';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DodoIndexRoute: typeof DodoIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DodoIndexRoute: DodoIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dodo/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dodo/": {
      "filePath": "dodo/index.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
